export const AdminConstant = {
    CHANGE_SHOWING_SECTION: "CHANGE SHOWING SECTION",
    CHANGE_TYPE_ON_VIEW: "CHANGE TYPE ON VIEW",
    ADD_ADMIN_DATA: "ADD ADMIN DATA",
    ADD_VEHICLE_OWNER: "ADD VEHICLE OWNER",
};
