export const CropConst = {
    ADD_CROPPED_DATA: 'ADD CROPPED DATA',
    ADD_UPLOADED_IMAGE: 'ADD UPLOAD IMAGE',
    CLEAR_CROPPED_IMAGE: 'CLEAR CROPPED DATA',
    CLEAR_UPLOADED_IMAGE: 'CLEAR UPLOADED IMAGE',
}