export const SignupConstants = {
    ADD_INIT_PLAN_INFO: "ADD INIT PLAN INFO",
    ADD_CONTANT_INFO: "ADD CONTACT INFO",
    ADD_DOMAIN_INFO: "ADD DOMAIN INFO",
    ADD_LOGIN_PASSWORD: "ADD LOGIN PASSWORD",
    ADD_PRICE_INFO: "ADD PRICE INFO",
};
